name: Export Secrets

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Generate .env
        shell: bash
        run: |
          {
            echo 'GOOGLE_CLIENT_EMAIL<<EOF'
            echo "${{ secrets.GOOGLE_CLIENT_EMAIL }}"
            echo 'EOF'

            echo 'GOOGLE_PRIVATE_KEY<<EOF'
            echo "${{ secrets.GOOGLE_PRIVATE_KEY }}"
            echo 'EOF'

            echo "HABLLA_BOARD_ID=${{ secrets.HABLLA_BOARD_ID }}"
            echo "HABLLA_EMAIL=${{ secrets.HABLLA_EMAIL }}"
            echo "HABLLA_PASSWORD=${{ secrets.HABLLA_PASSWORD }}"
            echo "HABLLA_TOKEN=${{ secrets.HABLLA_TOKEN }}"
            echo "HABLLA_WORKSPACE_ID=${{ secrets.HABLLA_WORKSPACE_ID }}"

            echo "SIGE_APP=${{ secrets.SIGE_APP }}"
            echo "SIGE_TOKEN=${{ secrets.SIGE_TOKEN }}"
            echo "SIGE_USER=${{ secrets.SIGE_USER }}"

            echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}"
            echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
            echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}"

            echo "ZENVIA_ACCESS_TOKEN=${{ secrets.ZENVIA_ACCESS_TOKEN }}"
            echo "ZENVIA_QUEUE_ID=${{ secrets.ZENVIA_QUEUE_ID }}"

            echo "ZOHO_ACCOUNT_OWNER=${{ secrets.ZOHO_ACCOUNT_OWNER }}"
            echo "ZOHO_CLIENT_ID=${{ secrets.ZOHO_CLIENT_ID }}"
            echo "ZOHO_CLIENT_SECRET=${{ secrets.ZOHO_CLIENT_SECRET }}"
            echo "ZOHO_LEADS_APP_NAME=${{ secrets.ZOHO_LEADS_APP_NAME }}"
            echo "ZOHO_LEADS_COLUMN_MAPPING=${{ secrets.ZOHO_LEADS_COLUMN_MAPPING }}"
            echo "ZOHO_LEADS_REPORT_NAME=${{ secrets.ZOHO_LEADS_REPORT_NAME }}"
            echo "ZOHO_REFRESH_TOKEN=${{ secrets.ZOHO_REFRESH_TOKEN }}"
            echo "ZOHO_SCHEDULING_APP_NAME=${{ secrets.ZOHO_SCHEDULING_APP_NAME }}"
            echo "ZOHO_SCHEDULING_COLUMN_MAPPING=${{ secrets.ZOHO_SCHEDULING_COLUMN_MAPPING }}"
            echo "ZOHO_SCHEDULING_REPORT_NAME=${{ secrets.ZOHO_SCHEDULING_REPORT_NAME }}"
          } > .env

      - name: Upload env file
        uses: actions/upload-artifact@v4
        with:
          name: exported-env
          path: .env
