name: Export ENV

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Create env file
        shell: bash
        run: |
          rm -f .env

          echo "GOOGLE_CLIENT_EMAIL=${{ secrets.GOOGLE_CLIENT_EMAIL }}" >> .env
          echo "GOOGLE_PRIVATE_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }}" >> .env

          echo "HABLLA_BOARD_ID=${{ secrets.HABLLA_BOARD_ID }}" >> .env
          echo "HABLLA_EMAIL=${{ secrets.HABLLA_EMAIL }}" >> .env
          echo "HABLLA_PASSWORD=${{ secrets.HABLLA_PASSWORD }}" >> .env
          echo "HABLLA_TOKEN=${{ secrets.HABLLA_TOKEN }}" >> .env
          echo "HABLLA_WORKSPACE_ID=${{ secrets.HABLLA_WORKSPACE_ID }}" >> .env

          echo "SIGE_APP=${{ secrets.SIGE_APP }}" >> .env
          echo "SIGE_TOKEN=${{ secrets.SIGE_TOKEN }}" >> .env
          echo "SIGE_USER=${{ secrets.SIGE_USER }}" >> .env

          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env

          echo "ZENVIA_ACCESS_TOKEN=${{ secrets.ZENVIA_ACCESS_TOKEN }}" >> .env
          echo "ZENVIA_QUEUE_ID=${{ secrets.ZENVIA_QUEUE_ID }}" >> .env

          echo "ZOHO_ACCOUNT_OWNER=${{ secrets.ZOHO_ACCOUNT_OWNER }}" >> .env
          echo "ZOHO_CLIENT_ID=${{ secrets.ZOHO_CLIENT_ID }}" >> .env
          echo "ZOHO_CLIENT_SECRET=${{ secrets.ZOHO_CLIENT_SECRET }}" >> .env
          echo "ZOHO_LEADS_APP_NAME=${{ secrets.ZOHO_LEADS_APP_NAME }}" >> .env
          echo "ZOHO_LEADS_COLUMN_MAPPING=${{ secrets.ZOHO_LEADS_COLUMN_MAPPING }}" >> .env
          echo "ZOHO_LEADS_REPORT_NAME=${{ secrets.ZOHO_LEADS_REPORT_NAME }}" >> .env
          echo "ZOHO_REFRESH_TOKEN=${{ secrets.ZOHO_REFRESH_TOKEN }}" >> .env
          echo "ZOHO_SCHEDULING_APP_NAME=${{ secrets.ZOHO_SCHEDULING_APP_NAME }}" >> .env
          echo "ZOHO_SCHEDULING_COLUMN_MAPPING=${{ secrets.ZOHO_SCHEDULING_COLUMN_MAPPING }}" >> .env
          echo "ZOHO_SCHEDULING_REPORT_NAME=${{ secrets.ZOHO_SCHEDULING_REPORT_NAME }}" >> .env

          ls -lah
          cat .env

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exported-env
          path: .env

      - name: Show download link
        run: |
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
