name: Hablla Clients

on:
  schedule:
    - cron: '02 3,9,15,21 * * *'
  workflow_dispatch:

concurrency:
  group: hablla-clients
  cancel-in-progress: false

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
      - name: Add random delay
        run: sleep $((RANDOM % 30 + 5))

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
        env:
          GIT_TRACE: 0
          GIT_CURL_VERBOSE: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node src/hablla/hablla-clients.js
        env:

          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

          HABLLA_TOKEN: ${{ secrets.HABLLA_TOKEN }}
          HABLLA_WORKSPACE_ID: ${{ secrets.HABLLA_WORKSPACE_ID }}